name: Generate Snk Animation

on:
  # 每 24 小时自动运行一次
  schedule:
    - cron: "0 */24 * * *"

  # 允许手动触发工作流
  workflow_dispatch:

  # 在 master 分支上的每次推送时运行
  push:
    branches:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10 # 设置超时时间为 10 分钟

    steps:
      # 根据 GitHub 用户（<github_user_name>）的贡献图生成一个贪吃蛇游戏，输出 SVG 动画到 <svg_out_path>
      - name: 生成 grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }} # 使用仓库所有者的用户名
          outputs: |
            dist/grid-snake.svg  # 输出普通主题的 SVG 文件
            dist/grid-snake-dark.svg?palette=github-dark  # 输出深色主题的 SVG 文件
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_GITHUB_TOKEN }} # 使用 GitHub 提供的默认令牌

      # 将 <build_dir> 中的内容推送到指定分支
      # 内容可以通过以下链接访问：
      # https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file>
      # 或者作为 GitHub Pages 访问
      - name: 将 grid-snake.svg 推送到 output 分支
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: main # 目标分支为 main
          build_dir: profile-snk # 要推送的目录为 profile-snk
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_GITHUB_TOKEN }} # 使用 GitHub 提供的默认令牌
